### ISSUE TITLE
Prediction Submission File Format

### ISSUE THREAD

**Issue by kari-chen** [Rochester-Biomedical-DS/Hackathon-Summer-2023#3]
Hello,

Should we submit the prediction file in a .csv or comma-delimited .txt file? We uploaded both file formats for now.

Thanks,
Kari

**Comment by amandalarracuente** [comment]
The scoring script will look for a file called prediction/prediction.csv. It must be formatted exactly the same way as the example file with the same number of rows (just with your predicted 0 and 1) or it will not be scored.
