### ISSUE TITLE
Leaderboard update

### ISSUE THREAD

**Issue by lnhtrn** [Rochester-Biomedical-DS/Hackathon-Summer-2023#5]
Hi, I updated my team's prediction at around 2:58 PM but the score on the leaderboard seems to be using the prediction file updated the day before. Is there any chance the leaderboard can be updated again, or does the leaderboard update using the prediction files submitted way earlier? I'm sorry for the trouble and thank you.

**Comment by amandalarracuente** [comment]
The timestamp on scores are for files pulled on: “18 August, 2023 15:00:03”
It looks like you posted within a minute of predictions being pulled. We'll repost scores from a few minutes after 3pm today  but tomorrow predictions will be pulled right at 3pm to make sure there is no lag, try to submit your predictions at least a few minutes before the deadline.
